float:
  any:
    - base_args: ['@metric']
      constructor: NSGLib
      disabled: false
      docker_tag: ann-benchmarks-nsg
      module: ann_benchmarks.algorithms.nsg
      name: nsg
      run_groups:
        1:
          arg_groups: [{knn: 200, L: 40, R: 50, C: 500}]
          args: {}
          query_args: [[40, 100, 200, 400, 600, 800, 1000]]
#        2:
#          arg_groups: [{knn: 200, L: 20, R: 30, C: 300}]
#          args: {}
#          query_args: [[40, 100, 200, 400, 600]]
#        3:
#          arg_groups: [{knn: 200, L: 60, R: 70, C: 700}]
#          args: {}
#          query_args: [[100, 200, 400, 600, 800]]
#        4:
#          arg_groups: [{knn: 400, L: 50, R: 60, C: 600}]
#          args: {}
#          query_args: [[100, 200, 400, 600, 800, 1000]]
#        5:
#          arg_groups: [{knn: 200, L: 80, R: 100, C: 800}]
#          args: {}
#          query_args: [[200, 400, 600, 800, 1000]]
